/*
Fleet Management Simple Metrics Server

Simple and correct implementation of the Fleet Management Metrics Coding Assessment

API version: 1.0.0
Contact: support@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetDeviceStatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceStatsResponse{}

// GetDeviceStatsResponse struct for GetDeviceStatsResponse
type GetDeviceStatsResponse struct {
	// returned as a time duration string. Eg: 5m10s
	AvgUploadTime string `json:"avg_upload_time"`
	// Uptime as a percentage. eg: 98.999
	Uptime float64 `json:"uptime"`
}

type _GetDeviceStatsResponse GetDeviceStatsResponse

// NewGetDeviceStatsResponse instantiates a new GetDeviceStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceStatsResponse(avgUploadTime string, uptime float64) *GetDeviceStatsResponse {
	this := GetDeviceStatsResponse{}
	this.AvgUploadTime = avgUploadTime
	this.Uptime = uptime
	return &this
}

// NewGetDeviceStatsResponseWithDefaults instantiates a new GetDeviceStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceStatsResponseWithDefaults() *GetDeviceStatsResponse {
	this := GetDeviceStatsResponse{}
	return &this
}

// GetAvgUploadTime returns the AvgUploadTime field value
func (o *GetDeviceStatsResponse) GetAvgUploadTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvgUploadTime
}

// GetAvgUploadTimeOk returns a tuple with the AvgUploadTime field value
// and a boolean to check if the value has been set.
func (o *GetDeviceStatsResponse) GetAvgUploadTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvgUploadTime, true
}

// SetAvgUploadTime sets field value
func (o *GetDeviceStatsResponse) SetAvgUploadTime(v string) {
	o.AvgUploadTime = v
}

// GetUptime returns the Uptime field value
func (o *GetDeviceStatsResponse) GetUptime() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value
// and a boolean to check if the value has been set.
func (o *GetDeviceStatsResponse) GetUptimeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uptime, true
}

// SetUptime sets field value
func (o *GetDeviceStatsResponse) SetUptime(v float64) {
	o.Uptime = v
}

func (o GetDeviceStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceStatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["avg_upload_time"] = o.AvgUploadTime
	toSerialize["uptime"] = o.Uptime
	return toSerialize, nil
}

func (o *GetDeviceStatsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"avg_upload_time",
		"uptime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDeviceStatsResponse := _GetDeviceStatsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDeviceStatsResponse)

	if err != nil {
		return err
	}

	*o = GetDeviceStatsResponse(varGetDeviceStatsResponse)

	return err
}

type NullableGetDeviceStatsResponse struct {
	value *GetDeviceStatsResponse
	isSet bool
}

func (v NullableGetDeviceStatsResponse) Get() *GetDeviceStatsResponse {
	return v.value
}

func (v *NullableGetDeviceStatsResponse) Set(val *GetDeviceStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceStatsResponse(val *GetDeviceStatsResponse) *NullableGetDeviceStatsResponse {
	return &NullableGetDeviceStatsResponse{value: val, isSet: true}
}

func (v NullableGetDeviceStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


