/*
Fleet Management Simple Metrics Server

Simple and correct implementation of the Fleet Management Metrics Coding Assessment

API version: 1.0.0
Contact: support@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UploadStatsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadStatsRequest{}

// UploadStatsRequest struct for UploadStatsRequest
type UploadStatsRequest struct {
	SentAt time.Time `json:"sent_at"`
	// the number of nanoseconds it took to upload a video
	UploadTime int32 `json:"upload_time"`
}

type _UploadStatsRequest UploadStatsRequest

// NewUploadStatsRequest instantiates a new UploadStatsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadStatsRequest(sentAt time.Time, uploadTime int32) *UploadStatsRequest {
	this := UploadStatsRequest{}
	this.SentAt = sentAt
	this.UploadTime = uploadTime
	return &this
}

// NewUploadStatsRequestWithDefaults instantiates a new UploadStatsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadStatsRequestWithDefaults() *UploadStatsRequest {
	this := UploadStatsRequest{}
	return &this
}

// GetSentAt returns the SentAt field value
func (o *UploadStatsRequest) GetSentAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value
// and a boolean to check if the value has been set.
func (o *UploadStatsRequest) GetSentAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SentAt, true
}

// SetSentAt sets field value
func (o *UploadStatsRequest) SetSentAt(v time.Time) {
	o.SentAt = v
}

// GetUploadTime returns the UploadTime field value
func (o *UploadStatsRequest) GetUploadTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UploadTime
}

// GetUploadTimeOk returns a tuple with the UploadTime field value
// and a boolean to check if the value has been set.
func (o *UploadStatsRequest) GetUploadTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadTime, true
}

// SetUploadTime sets field value
func (o *UploadStatsRequest) SetUploadTime(v int32) {
	o.UploadTime = v
}

func (o UploadStatsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadStatsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sent_at"] = o.SentAt
	toSerialize["upload_time"] = o.UploadTime
	return toSerialize, nil
}

func (o *UploadStatsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sent_at",
		"upload_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadStatsRequest := _UploadStatsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadStatsRequest)

	if err != nil {
		return err
	}

	*o = UploadStatsRequest(varUploadStatsRequest)

	return err
}

type NullableUploadStatsRequest struct {
	value *UploadStatsRequest
	isSet bool
}

func (v NullableUploadStatsRequest) Get() *UploadStatsRequest {
	return v.value
}

func (v *NullableUploadStatsRequest) Set(val *UploadStatsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadStatsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadStatsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadStatsRequest(val *UploadStatsRequest) *NullableUploadStatsRequest {
	return &NullableUploadStatsRequest{value: val, isSet: true}
}

func (v NullableUploadStatsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadStatsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


