/*
Fleet Management Simple Metrics Server

Simple and correct implementation of the Fleet Management Metrics Coding Assessment

API version: 1.0.0
Contact: support@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotFoundResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotFoundResponse{}

// NotFoundResponse struct for NotFoundResponse
type NotFoundResponse struct {
	Msg string `json:"msg"`
}

type _NotFoundResponse NotFoundResponse

// NewNotFoundResponse instantiates a new NotFoundResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotFoundResponse(msg string) *NotFoundResponse {
	this := NotFoundResponse{}
	this.Msg = msg
	return &this
}

// NewNotFoundResponseWithDefaults instantiates a new NotFoundResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotFoundResponseWithDefaults() *NotFoundResponse {
	this := NotFoundResponse{}
	return &this
}

// GetMsg returns the Msg field value
func (o *NotFoundResponse) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *NotFoundResponse) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *NotFoundResponse) SetMsg(v string) {
	o.Msg = v
}

func (o NotFoundResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotFoundResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["msg"] = o.Msg
	return toSerialize, nil
}

func (o *NotFoundResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"msg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotFoundResponse := _NotFoundResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotFoundResponse)

	if err != nil {
		return err
	}

	*o = NotFoundResponse(varNotFoundResponse)

	return err
}

type NullableNotFoundResponse struct {
	value *NotFoundResponse
	isSet bool
}

func (v NullableNotFoundResponse) Get() *NotFoundResponse {
	return v.value
}

func (v *NullableNotFoundResponse) Set(val *NotFoundResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNotFoundResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNotFoundResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotFoundResponse(val *NotFoundResponse) *NullableNotFoundResponse {
	return &NullableNotFoundResponse{value: val, isSet: true}
}

func (v NullableNotFoundResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotFoundResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


